apiVersion: apps/v1
kind: Deployment
metadata:
  name: rameshtraders-be
  labels:
    app: rameshtraders-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rameshtraders-be
  template:
    metadata:
      labels:
        app: rameshtraders-be
    spec:
      containers:
      - name: rameshtraders-be
        image: your-registry.com/rameshtraders-be:latest
        ports:
        - containerPort: 4001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4001"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: cloudinary-secret
              key: cloud_name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudinary-secret
              key: api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudinary-secret
              key: api_secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 4001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rameshtraders-be-service
spec:
  selector:
    app: rameshtraders-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
  type: LoadBalancer

